ARG BASE_TAG="latest"
ARG BASE_IMAGE="core"
FROM ghcr.io/zwpseudo/${BASE_IMAGE}:${BASE_TAG}
USER root

ENV HOME /home/hostlife-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

# Maltego wants a browser installed and the default is Firefox, Install Firefox
COPY ./src/ubuntu/install/firefox/ $INST_SCRIPTS/firefox/
COPY ./src/ubuntu/install/firefox/firefox.desktop $HOME/Desktop/
RUN bash $INST_SCRIPTS/firefox/install_firefox.sh && rm -rf $INST_SCRIPTS/firefox/

COPY ./src/ubuntu/install/maltego $INST_SCRIPTS/maltego/
RUN bash $INST_SCRIPTS/maltego/install_maltego.sh  && rm -rf $INST_SCRIPTS/maltego/

COPY ./src/ubuntu/install/maltego/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh
RUN chmod 755 $STARTUPDIR/custom_startup.sh


# Update the desktop environment to be optimized for a single application
RUN cp $HOME/.config/xfce4/xfconf/single-application-xfce-perchannel-xml/* $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
RUN apt-get remove -y xfce4-panel


######### End Customizations ###########

#ADD ./src/common/scripts $STARTUPDIR
RUN $STARTUPDIR/set_user_permission.sh $HOME

RUN chown 1000:0 $HOME

ENV HOME /home/hostlife-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
