ARG BASE_TAG="latest"
ARG BASE_IMAGE="core"
FROM ghcr.io/zwpseudo/${BASE_IMAGE}:${BASE_TAG}
USER root

ENV HOME /home/hostlife-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/
WORKDIR $HOME

######### Customize Container Here ###########


# Install Google Chrome
COPY ./src/ubuntu/install/chrome $INST_SCRIPTS/chrome/
RUN bash $INST_SCRIPTS/chrome/install_chrome.sh  && rm -rf $INST_SCRIPTS/chrome/

# Install Hunchly
COPY ./src/ubuntu/install/hunchly $INST_SCRIPTS/hunchly/
RUN bash $INST_SCRIPTS/hunchly/install_hunchly.sh  && rm -rf $INST_SCRIPTS/hunchly/

# To apply the Hunchly license into the image, replace the placeholder license.key file and uncomment the following lines
#RUN mkdir -p /opt/hunchly/ && echo "license_location=/opt/hunchly/license.key" >>/usr/lib/hunchly/hunchly.ini
#ADD ./src/ubuntu/install/hunchly/license.key /opt/hunchly/license.key


######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/hostlife-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
