ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-focal"
FROM ghcr.io/zwpseudo/${BASE_IMAGE}:${BASE_TAG}
USER root

ENV HOME /home/hostlife-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########


COPY ./src/ubuntu/install/deluge $INST_SCRIPTS/deluge/
RUN bash $INST_SCRIPTS/deluge/install_deluge.sh  && rm -rf $INST_SCRIPTS/deluge/

COPY ./src/ubuntu/install/deluge/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh
RUN chmod 755 $STARTUPDIR/custom_startup.sh


# Update the desktop environment to be optimized for a single application
RUN cp $HOME/.config/xfce4/xfconf/single-application-xfce-perchannel-xml/* $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
RUN apt-get remove -y xfce4-panel

######### End Customizations ###########

RUN chown 1000:0 $HOME

ENV HOME /home/hostlife-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
